### ISSUE TITLE
Obstacle prevention

### ISSUE THREAD

**Issue by SpAnDaNpAtIl** [satinder147/DeepWay.v2#1]
Can I know how exactly does it help in preventing obstacles with height of over 1m and greater so that the person using it never falls for it? I suggest detecting it and remove that patch off the model of road in which traveller will be walking till the obstacle is not overtaken.

**Comment by satinder147** [comment]
Right now, it will work only work on pedestrians, I have thought of something similar. I desire to use path planning using A*, but because I don't have any distance measurement sensor or any other method to generate a map of the world in front of me, it is difficult applying a algorithm like A* to get a smooth path around the surrounding. I am thinking of exploring stereo imagery.
